[package]
name = "chip8_assembler"
version = "0.1.0"
authors = ["david"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
nom = "3.2"
